[build]
  command = "npm run postinstall && rm -f Dockerfile docker-compose.yml README.md && rm -rf docker/"
  publish = "."

[[redirects]]
  from = "https://atomic-package.netlify.app/*"
  to = "https://atomic-package.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200