[build]
  command = "npm run postinstall && rm -f Dockerfile docker-compose.yml README.md && rm -rf docker/"
  publish = "."

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200