[build]
  command = "npm install --legacy-peer-deps"
  publish = "."

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200